name: resnet_v2_001_30jun2022
task: autoencoder
device: gpu
use_amp: False
# gpu_ids: [0] will be released in next versions. Use device instead

dataset:
  name: img
  path_dir: /home/manavendra/homeNN/Datasets/mounted/FFHQ
  batch_size: 1
  shuffle: True
  num_workers: 4

networks:
  ae:
    arch: ResnetAE_v2
    in_nc: 3
    mid_nc: 64
    out_nc: 3
    num_blocks: 3
    num_multiple: 2

    norm_type: group
    pad_type: zero
    act_type: gelu
    up_type: shuffle
    norm_groups: 4

    optimizer:
      name: adamw
      weight_decay: 0.001
      beta1: 0.9
      beta2: 0.99
      lr: 1e-3

    scheduler:
      # TODO: restart
      # TODO warm-up
      #scheme: linear
      #end_factor: 0.2

      scheme: multistep
      #milestones: []
      milestones_rel: [0.2, 0.4, 0.6, 0.8] 
      gamma: 0.5

lossers:
  l_gen:
    losser_type: image
    loss:
      pixel:
        criterion: {criterion_type: elastic, alpha: 0.8}
        weight: 1.0
      tv:
        criterion: {gamma: 0.8}
        weight: 0.001

      

weights: 
  ae: 
    path: '../experiments/ae_faces_22jun2022/models/ae.pth'
    strict: False

experiments:
  root: '../experiments/'
  saving_freq: 2000
  display_freq: 100

train:
  n_iters: 10000
  

logger:
  print_freq: 100
  save_log_file: True
   