name: ae_21jun2022
task: autoencoder
gpu_ids: []
dataset:
  name: a2b
  path_dir1: '/home/manavendra/homeNN/Datasets/cats_dogs/training_set/cats/'
  path_dir2:  '/home/manavendra/homeNN/Datasets/cats_dogs/training_set/dogs/'
  #path_test1: '/home/manavendra/homeNN/Datasets/cats_dogs/test_set/cats/'
  #path_test2: '/home/manavendra/homeNN/Datasets/cats_dogs/test_set/dogs/'
  batch_size: 32
  shuffle: True
  num_workers: 4

networks:
  autoencoder:
    arch: mysimpleCLNN
    in_nc: 3
    mid_nc: 32
    out_nc: 3

    loss:
      pixel:
        criterion: {criterion_type: l1, alpha: 0.5, beta: 0.7}
        weight: 1.0
      tv:
        criterion: {criterion_type: l1}
        weight: 0.002

    optimizer:
      name: adam
      beta1: 0.9
      beta2: 0.999
      lr: 1e-3

    scheduler:
      #scheme: linear
      #end_factor: 0.2

      scheme: multistep
      #milestones: []
      milestones_rel: [0.2, 0.4, 0.6, 0.8] 
      gamma: 0.5


weights: 
  #classificator: '../experiments/classificator_18jun2022sun/models/classificator.pth'

experiments:
  root: '../experiments/'
  checkpoint_freq: 1000

train:
  n_iters: 8000
  
loss:
  func_type: CrossEntropyLoss
  weight: 1.0
  #reduction: mean
  #pixel_criterion: l2
  #pixel_weight: 100.0

logger:
  print_freq: 10
  save_log_file: True
  #path_log_file: '../logs'
  