name: ae_21jun2022
task: autoencoder
gpu_ids: [0]
dataset:
  name: img
  path_dir: '/home/manavendra/homeNN/Datasets/cats_dogs/training_set/cats/'
  #path_dir2:  '/home/manavendra/homeNN/Datasets/cats_dogs/training_set/dogs/'
  #path_test1: '/home/manavendra/homeNN/Datasets/cats_dogs/test_set/cats/'
  #path_test2: '/home/manavendra/homeNN/Datasets/cats_dogs/test_set/dogs/'
  batch_size: 16
  shuffle: True
  num_workers: 4

networks:
  ae:
    arch: SimpleAEUnet
    in_nc: 3
    mid_nc: 32
    out_nc: 3

    losser_type: image
    loss:
      pixel:
        criterion: {criterion_type: l1}
        weight: 1.0
      tv:
        criterion: {gamma: 2}
        weight: 0.01

    optimizer:
      name: adam
      beta1: 0.9
      beta2: 0.999
      lr: 1e-3

    scheduler:
      #scheme: linear
      #end_factor: 0.2

      scheme: multistep
      #milestones: []
      milestones_rel: [0.2, 0.4, 0.6, 0.8] 
      gamma: 0.5


weights: 
  ae: '../experiments/ae_21jun2022/models/ae.pth'

experiments:
  root: '../experiments/'
  checkpoint_freq: 1000
  display_freq: 50

train:
  n_iters: 6000
  
#loss:
#  func_type: CrossEntropyLoss
#  weight: 1.0
  #reduction: mean
  #pixel_criterion: l2
  #pixel_weight: 100.0

logger:
  print_freq: 100
  save_log_file: True
  #path_log_file: '../logs'
   